services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/backend
    volumes:
      - ./backend:/var/www/backend
      - ./backend/vendor:/var/www/backend/vendor
      - ./backend:/var/www/backend:cached
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:iIwqmIdMBn82czbuhJCGAleckdOQRmYzWmv2If02P90=
      - DB_HOST=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=secret
    depends_on:
      - mysql
    networks:
      - laravel_network
      
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: vue_app
    restart: unless-stopped
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend
      - /var/www/frontend/node_modules
    networks:
      - laravel_network
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api

  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./backend:/var/www/backend
      - ./frontend/dist:/var/www/frontend/dist
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
      - node
    networks:
      - laravel_network

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel_user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - laravel_network

volumes:
  mysql_data:

networks:
  laravel_network:
    driver: bridge